version: '3.5'
services:
    nginx:
        build:
          context: .
          dockerfile: nginx.Dockerfile
        container_name: sanic_nginx_con
        ports:
            - "8888:80"
        links:
            - app
        networks:
          - sanic-net

    app:
        build:
          context: ./app
          dockerfile: Dockerfile
        container_name: sanic_url_con
        expose:
            - "8000"
        links:
            - postgres
        env_file:
            - ./.env
        depends_on:
            - postgres
        networks:
          - sanic-net
    postgres:
        build:
          context: ./sql
          dockerfile: Dockerfile
        container_name: sanic_db_con
        env_file:
            - ./.env
        volumes:
            - sanic-data:/var/lib/postgres/data
        expose:
            - "5432"
        networks:
          - sanic-net
networks:
  sanic-net:
    name: sanic-network
volumes:
  sanic-data:
    name: sanic-db
