---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-sanic-pv
spec:
  capacity:
    storage: 1Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  storageClassName: manual
  nfs:
    server: 172.27.100.204
    path: "/opt/nfsshare/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-sanic-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
